// ==========================================
// CONSTANTES GLOBAIS
// ==========================================

export const APP_VERSION = "v4.7.14"; // Fix Pump Reading

export const DADOS_INICIAIS = {
  chuvas: [],
  energia: [],
  documentos: [],
  abastecimentos: [],
  recomendacoes: [],
  refeicoes: [],
  compras: [],
  os: [],
};

export const ATIVOS_INICIAIS = {
  parametros: {
    estoque: { capacidadeTanque: "", estoqueMinimo: "", ajusteManual: "" },
    financeiro: { precoDiesel: "" },
    energia: { diaLeitura: "", metaConsumo: "", custoKwh: "" },
    manutencao: { alertaPreventiva: "" },
  },
  maquinas: [],
  talhoes: [],
  centrosCusto: [],
  produtos: [],
  locais: [],
  pontosEnergia: [],
  safras: [],
  culturas: [],
  classes: [],
  tiposDocumento: [],
  tiposRefeicao: [],
  operacoesAgricolas: [],
  setores: [],
  produtosManutencao: [],
};

export const DEFAULT_PERMISSIONS: any = {
  Proprietário: {
    screens: {
      dashboard: true,
      graficos: true,
      config: true,
      os: true,
      refeicoes: true,
      abastecimento: true,
      recomendacoes: true,
      estoque: true,
      manutencao: true,
      docs: true,
      energia: true,
      chuvas: true,
      mapa: true,
    },
    actions: {
      abastecimento_compra: true,
      estoque_compra: true,
      recomendacao_criar: true,
      chuvas_registro: true,
      mapa_edicao: true,
      excluir_registros: true,
      config_financeiro: true,
      config_equipe: true,
      config_propriedade: true,
      config_sistema: true,
    },
  },
  Gerente: {
    screens: {
      dashboard: true,
      graficos: true,
      config: false,
      os: true,
      refeicoes: true,
      abastecimento: true,
      recomendacoes: true,
      estoque: true,
      manutencao: true,
      docs: true,
      energia: true,
      chuvas: true,
      mapa: true,
    },
    actions: {
      abastecimento_compra: true,
      estoque_compra: true,
      recomendacao_criar: true,
      chuvas_registro: true,
      mapa_edicao: true,
      excluir_registros: false,
      config_financeiro: true,
      config_equipe: true,
      config_propriedade: true,
      config_sistema: true,
    },
  },
  Administrativo: {
    screens: {
      dashboard: true,
      graficos: true,
      config: false,
      os: true,
      refeicoes: true,
      abastecimento: true,
      recomendacoes: false,
      estoque: true,
      manutencao: false,
      docs: true,
      energia: true,
      chuvas: true,
      mapa: false,
    },
    actions: {
      abastecimento_compra: true,
      estoque_compra: true,
      recomendacao_criar: false,
      chuvas_registro: true,
      mapa_edicao: false,
      excluir_registros: false,
      config_financeiro: true,
      config_equipe: false,
      config_propriedade: true,
      config_sistema: false,
    },
  },
  Operador: {
    screens: {
      dashboard: false,
      graficos: false,
      config: false,
      os: true,
      refeicoes: true,
      abastecimento: true,
      recomendacoes: true,
      estoque: true,
      manutencao: true,
      docs: true,
      energia: true,
      chuvas: true,
      mapa: true,
    },
    actions: {
      abastecimento_compra: false,
      estoque_compra: false,
      recomendacao_criar: false,
      chuvas_registro: true,
      mapa_edicao: true,
      excluir_registros: false,
      config_financeiro: false,
      config_equipe: false,
      config_propriedade: false,
      config_sistema: false,
    },
  },
  "Consultor Agrícola": {
    screens: {
      dashboard: false,
      graficos: true,
      config: false,
      os: true,
      refeicoes: false,
      abastecimento: false,
      recomendacoes: true,
      estoque: true,
      manutencao: false,
      docs: true,
      energia: false,
      chuvas: true,
      mapa: true,
    },
    actions: {
      abastecimento_compra: false,
      estoque_compra: false,
      recomendacao_criar: true,
      chuvas_registro: true,
      mapa_edicao: true,
      excluir_registros: false,
      config_financeiro: false,
      config_equipe: false,
      config_propriedade: true,
      config_sistema: false,
    },
  },
};
